### PR TITLE
Replacement of "compile" with "implementation"

### PR DESCRIPTION
**Pull request by ardacebi**
As "compile" is going to be deprecated end-2018, this PR replaces with "implementation" that is the new usage.

### CODE REVIEW

**Comment by bryant1410** [comment]
Hey, thanks for the contribution!

Shouldn't it be `api` instead?

**Comment by ardacebi** [comment]
That can also be used, Android Studio gives the following warning when "compile" is used:

androidstudioss

So both will work.

**Comment by bryant1410** [comment]
Yeah, but conceptually `api` should be used. `implementation` exposes the transitive dependencies to the library users, which is not recommended as they should add them explicitely.

**Comment by bryant1410** [comment]
So, if both work, `api` should be the way to go.

**Comment by ardacebi** [comment]
You can merge now. Replaced implementation with api.

**Comment by bryant1410** [comment]
Thanks!

**Comment by bryant1410** [comment]
Sorry, it was the other way around, `implementation` should be used

palmface

**Comment by ardacebi** [comment]
@bryant1410 Told you :)

I said to use both of them after seeing Android Studio's output. I haven't seen the usage "api" anywhere. Look at a screenshot from my project:

build gradle

**Pull request merged**
